{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "content-delivery.serviceAccountName" . }}
  labels:
{{ include "content-delivery.labels" . | nindent 4 }}
{{- end -}}
