apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio-jhf.fullname" . }}
  labels:
    {{- include "portfolio-jhf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "portfolio-jhf.selectorLabels" . | nindent 4 }}
