{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "portfolio-jhf.serviceAccountName" . }}
  labels:
{{ include "portfolio-jhf.labels" . | nindent 4 }}
{{- end -}}
